### ISSUE TITLE
大家协调一致挺重要的

### ISSUE THREAD

**Issue by taocp** [bluebore/wangzherongyao#1]
青铜选手，请教一个问题。。。

某个场景下有2个选择A和B，一个是“最优选择”，一个是“次优选择”，

情况1

大家对A和B哪个是“最优”哪个是“次优”意见不一致（或者没有协调好），导致3个人做了A，另外2个选了B，这个时候可能这两拨人都没达成目的，甚至分别团灭了

情况2

大家一致选定了“次优选择”，结果达成

面临几个相差不是那么大的选择时，感觉大家协调一致更重要？

**Comment by bluebore** [comment]
一切皆有可能，如果次优选择也不错，协调一致当然最好。
但也有一些特殊情况，比如经济差距比较大的情况下， 如果有两个二愣子冲上去了，另外三个还是龟缩塔下守一波比较好，否则就团灭了。
